version: "3"

services:
  app:
    image: app:helloworld
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./opt/:/opt
      - app_node_modules:/opt/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

volumes:
  app_node_modules: